openapi: 3.0.0
info:
  description: Api Documentation
  version: 0.1.0
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
tags:
  - name: /clusters
servers:
  - url: /localhost

paths:
  /clusters:
    get:
      tags:
        - /clusters
      summary: getClusters
      operationId: getClusters
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cluster'
        401:
          description: Unauthorized
        403:
          description: Forbidden

components:
  schemas:

    Cluster:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        defaultCluster:
          type: boolean
        status:
          $ref: '#/components/schemas/ClusterStatus'
        brokerCount:
          type: integer
        onlinePartitionCount:
          type: integer
        topicCount:
          type: integer
        bytesInPerSec:
          type: integer
        bytesOutPerSec:
          type: integer
      required:
        - id
        - name
        - status

    ClusterStatus:
      type: string
      enum:
        - online
        - offline
