openapi: 3.0.0
info:
  description: Api Documentation
  version: 0.1.0
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
tags:
  - name: /clusters
servers:
  - url: /localhost

paths:
  /clusters:
    get:
      tags:
        - /clusters
      summary: getClusters
      operationId: getClusters
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cluster'

  /clusters/{clusterId}/metrics/broker:
    get:
      tags:
        - /clusters
      summary: getBrokersMetrics
      operationId: getBrokersMetrics
      parameters:
        - name: clusterId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrokerMetrics'

  /clusters/{clusterId}/topics:
    get:
      tags:
        - /clusters
      summary: getTopics
      operationId: getTopics
      parameters:
        - name: clusterId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topic'

  /clusters/{clusterId}/topics/{topicName}:
    get:
      tags:
        - /clusters
      summary: getTopicDetails
      operationId: getTopicDetails
      parameters:
        - name: clusterId
          in: path
          required: true
          schema:
            type: string
        - name: topicName
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicDetails'

components:
  schemas:
    Cluster:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        defaultCluster:
          type: boolean
        status:
          $ref: '#/components/schemas/ClusterStatus'
        brokerCount:
          type: integer
        onlinePartitionCount:
          type: integer
        topicCount:
          type: integer
        bytesInPerSec:
          type: integer
        bytesOutPerSec:
          type: integer
      required:
        - id
        - name
        - status

    ClusterStatus:
      type: string
      enum:
        - online
        - offline

    BrokerMetrics:
      type: object
      properties:
        clusterId:
          type: string
        bytesInPerSec:
          type: integer
        brokerCount:
          type: integer
        zookeeperStatus:
          type: integer
        activeControllers:
          type: integer
        uncleanLeaderElectionCount:
          type: integer
        networkPoolUsage:
          type: number
        requestPoolUsage:
          type: number
        onlinePartitionCount:
          type: integer
        underReplicatedPartitionCount:
          type: integer
        offlinePartitionCount:
          type: integer
        diskUsage:
          $ref: '#/components/schemas/DiskUsage'
        diskUsageDistribution:
          type: string
      required:
        - id

    DiskUsage:
      type: object
      properties:
        brokerId:
          type: int
        segmentSize:
          type: int

    Topic:
      type: object
      properties:
        clusterId:
          type: string
        name:
          type: string
        internal:
          type: boolean
        partitions:
          type: array
          items:
            $ref: '#/components/schemas/Partition'

    Partition:
      type: object
      properties:
        partition:
          type: int
        leader:
          type: int
        replicas:
          type: array
          items:
            $ref: '#/components/schemas/Replica'

    Replica:
      type: object
      properties:
        broker:
          type: int
        leader:
          type: boolean
        inSync:
          type: boolean

    TopicDetails:
      type: object
      properties:
        partitionCount:
          type: int
        replicationFactor:
          type: int
        replicas:
          type: int
        inSyncReplicas:
          type: int
        bytesInPerSec:
          type: int
        segmentSize:
          type: int
        segmentCount:
          type: int
        underReplicatedPartitions:
          type: int