kafka:
  clusters:
    -
      id: wrYGf-csNgiGdK7B_ADF7Z
      name: local
      bootstrapServers: localhost:9092
      jmxHost: localhost
      jmxPort: 9997
      zookeeper: localhost:2181
    -
      id: dMMQx-WRh77BKYas_g2ZTz
      name: secondLocal
      bootstrapServers: localhost:9093
      jmxHost: localhost
      jmxPort: 9998
      zookeeper: localhost:2182